# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-04 16:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0001_squashed_0094_auto_20180910_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='changed_staging_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        )
    ]
