# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-16 18:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0096_merge_20181222_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='changed_staging_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        )
    ]
